files:
  - source: /openHAB/Resources/en.lproj/*.strings
    translation: /openHAB/Resources/%two_letters_code%.lproj/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt: pt-PT
        sv: sv-SE
