name: Unit Tests

on:
  workflow_dispatch
  # push:
  #   branches:
  #     - develop
  #   tags-ignore:
  #     - '**'

jobs:
  build_and_test:
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: latest-stable

      - uses: actions/checkout@v2

      - name: Cache cocoapods dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-cocoapods-dependencies
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ env.cache-name }}-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-${{ env.cache-name }}-

      - name: Install Bundler
        run: gem install bundler

      - name: Bundle Install
        run: bundle install

      - name: Check Pods existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "Pods"

      - name: Install Dependencies
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          bundle exec pod install --repo-update
        shell: bash

      - name: Fastlane unit tests
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: unittests
          skip-tracking: true
