name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build app
      run: |
        fastlane run build_app(scheme: "openHAB", clean: true, export_method: "app-store")
#- name: Build
#      run: swift build -v
#    - name: Run tests
#      run: swift test -v
